"use strict";
exports.__esModule = true;
var a = 10;
console.log(a);
var s = 'hello';
var b = true;
var nu = null;
var un = undefined;
var arrayOfNumber = [1, 2, 3];
var arrayOfString = ['a', 'b', 'c'];
console.log(arrayOfNumber);
console.log(arrayOfString);
